"""Thêm bảng Medicine

Revision ID: c9752fdc0c5a
Revises: a0599a1abdca
Create Date: 2026-04-01 00:32:37.971567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9752fdc0c5a'
down_revision = 'a0599a1abdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicine_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_name'))

    op.drop_table('medicine')
    # ### end Alembic commands ###
